name: Build and Publish

on:
  # Run it on push to main branch
  push:
    branches: [main]
  # Run it during Pull request
  pull_request:

jobs:
  # Define job to build and publish docker image
  build-and-publish-docker-image:
    name: Build Docker Image and Push it to the repository
    runs-on: ubuntu-latest

    # Steps to perform in the said job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up the Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up Docker build
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      # Set up the build and push
      - name: Build Image and Push to Docker Hub
        uses: docker/build-push-action@v3
        with: 
          # Relative path of Dockerfile
          context: .
          file: ./Dockerfile
          push : true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-fastapi:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}